DROP TABLE info IF EXISTS;

CREATE TABLE info (
  name VARCHAR(20) NOT NULL,
  PRIMARY KEY(name)
);

INSERT INTO info VALUES('Dilbert');
INSERT INTO info VALUES('Dogbert');
INSERT INTO info VALUES('Catbert');
